### PR TITLE
Azure Active Directory Support

### PR DESCRIPTION
**Pull request by sharpjs**
This PR continues the work by @Jezour in #1.

### CODE REVIEW

**Comment by sharpjs** [comment]
@Jezour: I took your PR and modified it quite a bit to suit my vision for this module.  Will this still work for you?  If not, please let me know what you'd like changed.

**Comment by Jezour** [comment]
> @Jezour: I took your PR and modified it quite a bit to suit my vision for this module. Will this still work for you? If not, please let me know what you'd like changed. 

In my original PR I was possible to call something like this:

```
$password = ConvertTo-SecureString 'XXXX' -AsPlainText -Force;
$AadCredential = New-Object System.Management.Automation.PSCredential 'DataRefreshExtUsrManager@orixxx.com',$password;

$c = New-SqlContext -ServerName onlinetestdbpoolwe.database.windows.net -DatabaseName master -Credential $AadCredential -UseAzureActiveDirectoryPassword
Invoke-Sql -Sql "select name from sys.databases" -Context $c
```
In the last version is the AzureAuthenticationMode for sam.ActiveDirectoryPassword working only in case of using switch "-Azure".
The set for the server name is private. 
`public string ServerFullName { get; private set; }
`
My AAD user is able to connect to the database via AAD, but not to connect to the Azure to select resources. 
(due to security reasons...)

**Comment by sharpjs** [comment]
> My AAD user is able to connect to the database via AAD, but not to connect to the Azure to select resources.
> (due to security reasons...)

Ah, I understand.  The `AzureSqlContext` class is intended to work for _all_ connections to Azure SQL Database, so there is a single place for Azure-specific connection options.  I did not consider that there could be users in your situation: able to authenticate to Azure SQL Database via AAD, but unable to use the Az modules.  The use of the Az module is only for convenience, to get the `ServerFullName` automatically based on the resource group and server short-names.  I can easily make that optional, so you can use the `-Azure` mode directly.

Here's how it works now:

```powershell
$c = New-SqlContext -Azure -ResourceGroupName foo -ServerName bar ...
# ...but it requires Get-AzSqlServer
```

I can make this possible too:

```powershell
$c = New-SqlContext -Azure -ServerName bar.database.windows.net ...
# No Az required!
```

**Comment by Jezour** [comment]
It would be nice. Ideal way without mandatory 
`-ResourceGroupName foo`

Btw Few examples of execution in the readme of the repo can make your wonderful work even more attractive.
(Thanks for this repo!)

**Comment by sharpjs** [comment]
Yep, missing documentation is the main reason why I haven't yet marked this 1.0.

**Comment by Jezour** [comment]
Hi @sharpjs !

I'm trying to solve it to make my scenario working with respect to your changes in the branch. 
Honestly, I'm most likely missing some kind of big picture. 

Can you help me to understand why is defined the ServerFullName? The ServerName from the base class seems to be sufficient. 
You have most likely some better ideas.
Well, I understand that ServerFullName should be not editable, but filled by PowerShell Get-AzSqlServer function.
On the other hand, I need to propagate the ServerName to skip using this Get-AzSqlServer.

I'm sorry my silly idea. I try to change:
`builder.DataSource = ServerFullName ?? ResolveServerFullName();`
to 
`builder.DataSource = ServerName ?? (ServerFullName ?? ResolveServerFullName());`

or change the getter somehow
`public string ServerFullName { get; private set; }`
to
```
        public string ServerFullName {
            get {return ServerFullName ?? base.ServerName; }
            private set;
        }

```

Unfortunately, I feel these changes like backward of changes in your nice code.
I do have a moral issue to make any of these changes as a commit. 
It seems that I have to wait.

**Comment by sharpjs** [comment]
@Jezour: OK, I've made `-ResourceGroupName` optional.  If you do not supply it, the `New-SqlContext` command treats `-ServerName` as the server full name without any fancy resolving.

**Comment by sharpjs** [comment]
Gonna merge this now.  Thanks for your help.  Next steps for this little project are README and CI via GitHub Actions.

**Comment by Jezour** [comment]
@sharpjs Thank you! It works.

**Comment by Jezour** [comment]
@sharpjs Can you please share the latest version into the PSGallery?
Maybe I'm missing something, but the version Prerelease   = 'master.b.5' seems to be missing in the PSGallery.
```
Find-Module PSql -AllowPrerelease -Repository PSGallery -Verbose -AllVersions | Select-Object -Property Version, PublishedDate

Version       PublishedDate
-------       -------------
2.0.0-pre01   8/21/2020 8:49:07 PM
2.0.0-alpha05 8/5/2020 9:39:38 PM
2.0.0-alpha04 8/4/2020 11:29:45 PM
2.0.0-alpha03 8/4/2020 10:55:27 PM
2.0.0-alpha02 8/4/2020 8:33:20 PM
```
Thanks again!

**Comment by sharpjs** [comment]
Yep! I will publish a `pre02` soon.

**Comment by sharpjs** [comment]
[Package published](https://www.powershellgallery.com/packages/PSql/2.0.0-pre02).

**Pull request merged**
